// Icon set codegen — Epic 13
// Spec: PRD-UI-SHELL.md §9 (self-hosted inline SVG)
//
// Reads the whitelisted Lucide icons out of `lucide-static` and emits a TS map
// of their inner markup, which `<app-icon>` inlines. Only the icons listed here
// ship — the other ~1975 never enter the bundle.
//
// We take the icons, not `lucide-angular`: that wrapper peers
// `@angular/core: 13.x - 21.x` and would cap the workspace at Angular 21,
// becoming a second upgrade gate beside `@ngrx/signals`. `lucide-static` has no
// peers, so it can never gate an Angular major.
//
// Output is committed, not built on every run: the set changes about never.
// Regenerate with `node tools/gen-icons.mjs` from `apps/app` after editing ICONS.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(here, '..');
const workspaceRoot = resolve(projectRoot, '../..');
const iconDir = resolve(workspaceRoot, 'node_modules/lucide-static/icons');

/**
 * Our name -> Lucide's name. The indirection is the point: swapping icon sets
 * later edits this map, not every template.
 */
const ICONS = {
  // nav modules (the rail, and the mobile switcher's composite glyph)
  songs: 'music',
  songbooks: 'library-big',
  stage: 'mic-vocal',
  audience: 'users',
  settings: 'settings',
  // shell chrome
  menu: 'menu',
  more: 'ellipsis',
  close: 'x',
  help: 'circle-help',
  search: 'search',
  // module + editor actions
  add: 'plus',
  download: 'download',
  undo: 'undo-2',
  redo: 'redo-2',
  transposeUp: 'arrow-up',
  transposeDown: 'arrow-down',
  favorite: 'star',
  title: 'type',
  reset: 'rotate-ccw',
};

/** Strip the wrapper <svg> and the license comment; keep the drawing only. */
function innerMarkup(name) {
  const svg = readFileSync(resolve(iconDir, `${name}.svg`), 'utf8');
  const body = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!body) {
    throw new Error(`Could not parse ${name}.svg`);
  }
  return body[1]
    .replace(/<!--[\s\S]*?-->/g, '')
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .join('');
}

const entries = Object.entries(ICONS)
  .map(([our, lucide]) => `  ${our}: '${innerMarkup(lucide)}',`)
  .join('\n');

const out = `// GENERATED by tools/gen-icons.mjs — do not edit by hand.
// Lucide (ISC) via lucide-static. Regenerate: node tools/gen-icons.mjs

/** Inner SVG markup per icon, drawn on a 24x24 viewBox with currentColor. */
export const ICON_SET = {
${entries}
} as const;

export type IconName = keyof typeof ICON_SET;
`;

const outDir = resolve(projectRoot, 'src/app/primitives/icon');
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'icon-set.generated.ts'), out);
console.log(`Wrote ${Object.keys(ICONS).length} icons.`);
